"""
This module provides functionality to save the traits of a triangle generated by a function to 
various formats and generate reports.
Functions:
    SingleMake(fun: tgen) -> None:
        Saves the traits of the triangle 'fun' to a database, a CSV file, and a Markdown file.
        Then the HTML file is created/updated and the traits statistics are displayed.
Usage:
    The module can be executed as a script. When executed, it will generate and process 
    the traits of a triangle using the 'Powers' generator from the 'Powers' module.
"""

from _tablmake import MakeTabl
from tabl import *

# Make sure that everything is up to date but do not include
# 'MakeTabl' in 'SingleMake' as this would be circular.
MakeTabl()


# #@


def SingleMake(fun: tgen) -> None:
    """
    - Saves the traits of the triangle 'fun' to a database, a CSV file, and Markdown file.
    - Then the HTML file is created/updated.
    - The traits statistics is displayed.

    Args:
        fun (tgen): The generator of the triangle.

    Returns:
        None
    """
    SaveTraitsToDB(fun)
    ConvertDBtoCSVandMD(GetDataPath(fun.id, "db"), fun.id)
    CsvToHtml(fun)
    StatisticReport(fun, True)
    SummaryReport(fun.id)


if __name__ == "__main__":
    from Powers import Powers as triangle
    SingleMake(triangle)
