"""
This module provides various functions to compute different types of sums on rows of tables.
Functions:
    even_sum(r: trow) -> int:
        Returns the sum of elements at even indices in the row.
    even_sum_(g: rgen, index: int) -> int:
        Returns the sum of elements at even indices in the row generated by the generator function.
    odd_sum(r: trow) -> int:
        Returns the sum of elements at odd indices in the row.
    odd_sum_(g: rgen, index: int) -> int:
        Returns the sum of elements at odd indices in the row generated by the generator function.
    antidiag_sum(r: trow) -> int:
        Returns the sum of all elements in the row.
    antidiag_sum_(g: rgen, n: int) -> int:
        Returns the sum of elements in the antidiagonal of the table generated by the generator function.
    acc_sum(r: trow) -> int:
        Returns the sum of accumulated sums of the row.
    acc_sum_(g: rgen, index: int) -> int:
        Returns the sum of accumulated sums of the row generated by the generator function.
    accrev_sum(r: trow) -> int:
        Returns the sum of accumulated sums of the reversed row.
    accrev_sum_(g: rgen, index: int) -> int:
        Returns the sum of accumulated sums of the reversed row generated by the generator function.
    alt_sum(r: trow) -> int:
        Returns the alternating sum of elements in the row (even indices minus odd indices).
    alt_sum_(g: rgen, index: int) -> int:
        Returns the alternating sum of elements in the row generated by the generator function.
    abs_sum(r: trow) -> int:
        Returns the sum of absolute values of elements in the row.
    abs_sum_(g: rgen, index: int) -> int:
        Returns the sum of absolute values of elements in the row generated by the generator function.
    RowSum(T: tabl) -> trow:
        Returns a list of sums of each row in the table.
    RowSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of each row generated by the generator function.
    EvenSum(T: tabl) -> trow:
        Returns a list of sums of elements at even indices for each row in the table.
    EvenSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of elements at even indices for each row generated by the generator function.
    OddSum(T: tabl) -> trow:
        Returns a list of sums of elements at odd indices for each row in the table.
    OddSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of elements at odd indices for each row generated by the generator function.
    AltSum(T: tabl) -> trow:
        Returns a list of alternating sums of elements for each row in the table.
    AltSum_(g: rgen, size: int) -> trow:
        Returns a list of alternating sums of elements for each row generated by the generator function.
    AbsSum(T: tabl) -> trow:
        Returns a list of sums of absolute values of elements for each row in the table.
    AbsSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of absolute values of elements for each row generated by the generator function.
    AccSum(T: tabl) -> trow:
        Returns a list of sums of accumulated sums for each row in the table.
    AccSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of accumulated sums for each row generated by the generator function.
    AccRevSum(T: tabl) -> trow:
        Returns a list of sums of accumulated sums of reversed rows for each row in the table.
    AccRevSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of accumulated sums of reversed rows for each row generated by the generator function.
    DiagSum(T: tabl) -> trow:
        Returns a list of sums of elements in the antidiagonals of the table.
    DiagSum_(g: rgen, size: int) -> trow:
        Returns a list of sums of elements in the antidiagonals of the table generated by the generator function.
    PrintSums(T: tabl, trianglename: str, mdformat: bool = True) -> None:
        Prints the sums of various traits for the given table. If mdformat is True, prints in markdown format.
"""

from typing import Callable
from itertools import accumulate
from _tabltypes import tabl, trow, rgen


# #@


def even_sum(r: trow) -> int:
    return sum(r[::2])


def even_sum_(g: rgen, index: int) -> int:
    return even_sum(g(index))


def odd_sum(r: trow) -> int:
    return sum(r[1::2])


def odd_sum_(g: rgen, index: int) -> int:
    return odd_sum(g(index))


def antidiag_sum(r: trow) -> int:
    return sum(r)


def antidiag_sum_(g: rgen, n: int) -> int:
    return sum(g(n - k)[k] for k in range((n + 2) // 2))


def acc_sum(r: trow) -> int:
    return sum(accumulate(r))


def acc_sum_(g: rgen, index: int) -> int:
    return acc_sum(g(index))


def accrev_sum(r: trow) -> int:
    return sum(accumulate(reversed(r)))


def accrev_sum_(g: rgen, index: int) -> int:
    return acc_sum(g(index))


def alt_sum(r: trow) -> int:
    return even_sum(r) - odd_sum(r)


def alt_sum_(g: rgen, index: int) -> int:
    return alt_sum(g(index))


def abs_sum(r: trow) -> int:
    return sum(abs(t) for t in r)


def abs_sum_(g: rgen, index: int) -> int:
    return abs_sum(g(index))


def RowSum(T: tabl) -> trow:
    return [sum(row) for row in T]


def RowSum_(g: rgen, size: int) -> trow:
    return [sum(g(n)) for n in range(size)]


def EvenSum(T: tabl) -> trow:
    return [even_sum(row) for row in T]


def EvenSum_(g: rgen, size: int) -> trow:
    return [even_sum(g(n)) for n in range(size)]


def OddSum(T: tabl) -> trow:
    return [odd_sum(row) for row in T]


def OddSum_(g: rgen, size: int) -> trow:
    return [odd_sum(g(n)) for n in range(size)]


def AltSum(T: tabl) -> trow:
    return [alt_sum(row) for row in T]


def AltSum_(g: rgen, size: int) -> trow:
    return [alt_sum(g(n)) for n in range(size)]


def AbsSum(T: tabl) -> trow:
    return [abs_sum(row) for row in T]


def AbsSum_(g: rgen, size: int) -> trow:
    return [abs_sum(g(n)) for n in range(size)]


def AccSum(T: tabl) -> trow:
    return [acc_sum(row) for row in T]


def AccSum_(g: rgen, size: int) -> trow:
    return [acc_sum(g(n)) for n in range(size)]


def AccRevSum(T: tabl) -> trow:
    return [accrev_sum(row) for row in T]


def AccRevSum_(g: rgen, size: int) -> trow:
    return [accrev_sum(g(n)) for n in range(size)]


def DiagSum(T: tabl) -> trow:
    def row(n: int) -> list[int]:
        return [T[n - k - 1][k] for k in range((n + 1) // 2)]

    return [sum(row(n)) for n in range(1, len(T) + 1)]


def DiagSum_(g: rgen, size: int) -> trow:
    return [antidiag_sum_(g, n) for n in range(size)]


def PrintSums(T: tabl, trianglename: str, mdformat: bool = True) -> None:
    SUMTRAIT: dict[str, Callable[[tabl], trow]] = {}

    def RegisterSumTrait(f: Callable[[tabl], trow]) -> None:
        SUMTRAIT[f.__name__] = f

    RegisterSumTrait(RowSum)
    RegisterSumTrait(EvenSum)
    RegisterSumTrait(OddSum)
    RegisterSumTrait(AltSum)
    RegisterSumTrait(AbsSum)
    RegisterSumTrait(AccSum)
    RegisterSumTrait(AccRevSum)
    RegisterSumTrait(DiagSum)

    if mdformat:
        # print("#", trianglename, ": Sums")
        print("| Trait        |   Seq  |")
        print("| :---         |  :---  |")
        for traitname, trait in SUMTRAIT.items():
            print(f"| {traitname:<12} | {trait(T)} |")
    else:
        for traitname, trait in SUMTRAIT.items():
            print(f'{trianglename + ":" + traitname:<18} {trait(T)}')


if __name__ == "__main__":
    from Abel import Abel
    from Bell import Bell

    PrintSums(Abel.tab(8), Abel.id)
    PrintSums(Bell.tab(6), Bell.id, False)
